mia-platform/lc39

docs/main-entrypoint.md
=> Add return type in examples

CHANGELOG.md, lib/launch-fastify.js, lib/status-routes.js, package.json
=> Allowing log level config for status routes

CHANGELOG.md, lib/launch-fastify.js, lib/options-extractors.js, package.json, tests/launch-fastify.test.js, tests/modules/immediate-close-module.js, tests/options-extractors.test.js
=> Ac 1402 nodeservice downtime

lib/custom-logger.js, tests/launch-fastify.test.js
Also url current info is the path so I've changed `url.full` to `url.path`
=> fix(BMP-150): added request information to request completed log

docs/main-entrypoint.md, lib/launch-fastify.js, lib/metrics-routes.js, package.json, tests/metrics.test.js, tests/modules/custom-metrics.js
=> Integrate prometheus. Allow custom metrics

bin/cli.js, lib/launch-fastify.js, tests/metrics.test.js
=> Exporse /-/metrics under feature flag

CHANGELOG.md, lib/custom-logger.js, tests/launch-fastify.test.js
Moved userAgent property inside of request property.
=> FIX(BMP-508): modified userAgent log level

docs/logging.md, lib/custom-logger.js, package.json, tests/launch-fastify.test.js, tests/log.schema.json, tests/modules/correct-module.js
Now bytes log will be converted from string to integer.
[BMP-587](https://makeitapp.atlassian.net/browse/BMP-587)
@fredmaggiowski
=> CHANGE(BMP-508): added conversion from string to int for bytes log

CHANGELOG.md, docs/main-entrypoint.md, lib/launch-fastify.js, tests/modules/module-with-transform-schema.js, tests/transform-schema.test.js
=> feat(MFD-17): trasformSchemaForSwagger

.gitignore, bin/cli.js, lib/custom-logger.js, lib/launch-fastify.js, lib/options-extractors.js, tests/launch-fastify.test.js
This PR doesn't include new functionalities, but just little refactors.
=> Lc39 refactor

CHANGELOG.md, bin/cli.js, index.js, package.json, tests/metrics.test.js, tests/transform-schema.test.js
=> chore: update deps

CHANGELOG.md, tests/launch-fastify.test.js
=> improved changelog

lib/custom-logger.js, package.json, tests/custom-logger.test.js, tests/launch-fastify.test.js, tests/log.schema.json, tests/modules/correct-module.js
=> feat: add params to log objects

CHANGELOG.md, docs/main-entrypoint.md, lib/launch-fastify.js, lib/metrics-routes.js, tests/metrics.test.js, tests/modules/custom-metrics-with-options.js
=> feat: add custom options passed to metrics

package.json, tests/launch-fastify.test.js, tests/modules/correct-module.js
This PR is to check that correct oas or swagger file are generated. With a `fastify-swagger` version before 4.12.2, adding the schema through fastify would have generated a wrong specification.
=> test: add test on oas to check it is correctly generated

CHANGELOG.md, docs/service-options.md, lib/launch-fastify.js
=> Added custom refResolver to fastifySwagger

.github/workflows/node.js.yml, CHANGELOG.md, docs/main-entrypoint.md, lib/import-env.js, lib/launch-fastify.js, package.json, tests/log.schema.json, tests/modules/module-with-transform-schema.js
=> upgrade deps and fix log schema

CHANGELOG.md, lib/custom-logger.js
=> removed: math round

lib/custom-logger.js, package.json, tap-snapshots/tests/custom-logger.test.js.test.cjs, tests/custom-logger.test.js, tests/modules/correct-module.js, tests/oas-ref-resolver.test.js
=> Added new keys to redact

docs/logging.md
Fix link to reflect the new page structure of the monitoring section.
=> fix link to documentation

CHANGELOG.md, lib/custom-logger.js, tap-snapshots/tests/custom-logger.test.js.test.cjs, tests/custom-logger.test.js, tests/modules/correct-module.js, tests/oas-ref-resolver.test.js
=> feat: add custom serializer for log with field error

CHANGELOG.md, bin/cli.js, package.json
=> remove make-promises-safe

CHANGELOG.md, lc39.d.ts, test-d/index.d-test.ts
=> export lc39 options type

.github/workflows/codeql.yml
=> feat: create codeql.yml

CHANGELOG.md, lib/launch-fastify.js
=> fix issue #308

.github/workflows/node.js.yml, CHANGELOG.md, example/index.js, example/package.json, package.json, tap-snapshots/tests/documentation-routes.test.js.test.cjs, tests/launch-fastify.test.js, tests/modules/immediate-close-module.js, tests/oas-ref-resolver.test.js
=> upgrade dependencies

.nvmrc, CHANGELOG.md, bin/cli.js, lib/launch-fastify.js, tests/documentation-routes.test.js
=> feat(cli): introduce option to disable the generation of endpoints OpenAPI specification

lib/launch-fastify.js, tap-snapshots/tests/documentation-routes.test.js.test.cjs, tests/oas-ref-resolver.test.js, tests/transform-schema.test.js
=> Fixed exposed HEAD routes

CHANGELOG.md, package.json
=> Bump v8.0.1

.github/workflows/node.js.yml, .gitignore, CHANGELOG.md, lib/custom-logger.js, package.json, tap-snapshots/tests/custom-logger.test.js.test.cjs, tap-snapshots/tests/documentation-routes.test.js.test.cjs
Also, resolve a critical dev dependency vulnerability updating tap
=> fix: getResponseTime deprecation warning
